# Generated by Django 2.0.7 on 2018-07-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='digest',
        ),
    ]
