# Generated by Django 2.1.5 on 2019-04-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '原创'), (1, '转发'), (2, '置顶')], default=0, verbose_name='类型'),
        ),
    ]
