# Generated by Django 2.1.5 on 2019-04-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '原'), (1, '转'), (2, '顶')], default=0, verbose_name='类型'),
        ),
    ]
