# Generated by Django 2.1.5 on 2019-03-31 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='文章名称')),
                ('body', models.TextField(verbose_name='正文')),
                ('visiting', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='访问量')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_post', to='topic.Post', verbose_name='父亲文章')),
                ('prev_post', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_post', to='topic.Post', verbose_name='前一篇文章')),
            ],
            options={
                'verbose_name': '专题文章',
                'verbose_name_plural': '专题文章',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='专题名')),
            ],
            options={
                'verbose_name': '专题分类',
                'verbose_name_plural': '专题分类',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic', verbose_name='所属专题'),
        ),
    ]
